# Generated by Django 4.2.4 on 2023-08-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dataviz',
            table='json_data',
        ),
    ]
